### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [faha1999/interactive-comments-section#4]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by faha1999** [comment]
@codehangen follow this [url](https://www.frontendmentor.io/challenges/interactive-comments-section-iG1RugEG9) , you'll find this challenge. 

- Yeah, this challenge is active.

**Comment by ghost** [comment]
Hi faha1999.

> @codehangen follow this [url](https://www.frontendmentor.io/challenges/interactive-comments-section-iG1RugEG9) , you'll find this challenge.
> Yeah, this challenge is active.

thank you for feedback.
